package za.ac.cput.linkup.domain;

public enum Course {
    BA_IN_PSYCHOLOGY,
    BA_IN_POLITICAL_SCIENCE,
    BA_IN_SOCIOLOGY,
    BA_IN_INTERNATIONAL_RELATIONS,

    BCOM_IN_ACCOUNTING,
    BCOM_IN_ECONOMICS,
    BCOM_IN_FINANCE,
    BCOM_IN_MARKETING,

    BSC_IN_COMPUTER_SCIENCE,
    BSC_IN_MATHEMATICS,
    BSC_IN_PHYSICS,
    BSC_IN_CHEMISTRY,

    BACHELOR_OF_ENGINEERING_IN_CIVIL_ENGINEERING,
    BACHELOR_OF_ENGINEERING_IN_MECHANICAL_ENGINEERING,
    BACHELOR_OF_ENGINEERING_IN_ELECTRICAL_AND_ELECTRONIC,
    BACHELOR_OF_ENGINEERING_IN_CHEMICAL_ENGINEERING,

    BACHELOR_OF_MEDICINE_AND_BACHELOR_OF_SURGERY,
    BACHELOR_OF_NURSING,
    BACHELOR_OF_PHARMACY,
    BACHELOR_OF_OCCUPATIONAL_THERAPY,

    BACHELOR_OF_EDUCATION_IN_FOUNDATION_PHASE,
    BACHELOR_OF_EDUCATION_IN_INTERMEDIARY_PHASE,
    BACHELOR_OF_EDUCATION_IN_SENOIR_AND_FET_PHASE,
    BACHELOR_OF_EDUCATION_IN_HONOURS_IN_EDUCATIONAL_PSYCHOLOGY,

    BACHELOR_OF_LAWS,
    BACHELOR_OF_ARTS_WITH_LAW_AS_AS_MAJOR,
    BACHELOR_OF_COMMERCE_WITH_LAW_AS_AS_MAJOR,

    BA_IN_FILM_AND_TELEVISION,
    BA_IN_THEATRE_AND_PERFORMANCE,
    BA_IN_FASHION,
    BA_IN_VISUAL_COMMUNICATION_DESIGN;
}
